### ISSUE TITLE
stealth /shadowform

### ISSUE THREAD

**Issue by frostmourne** [tobmaps/TrinityCore#54]
If you have been affected by faeriefire by any druid,you are not able to use stealth even if the debuff run out...I hope you understand what i mean: D

Not related to this bug but also very irritating:
sometimes you're not able to switch into shadowform as priest, if you used any holy spell in shadowform

Hope you'll find any solution for these bugs
I'm very gratefull for your help and best wishes

**Comment by tobmaps** [comment]
```
If you have been affected by faeriefire by any druid,you are not able to use stealth even if the debuff run out...I hope you understand what i mean: D
```

can't reproduce. I've removed this buff by Cloak of Shadows and used Stealth as usually - all ok here.
also tried to use healing spells in Shadowform - it correctly removed from me and i can enter to this form again without any problems. 

What revision your are using? I think all of these bugs are fixed in https://github.com/TrinityCore/TrinityCore/commit/cb3e6dbce325290fd649ce469adc253fee54f844

If no - then provide more detailed info about how to reproduce

**Comment by frostmourne** [comment]
I`m using the latest revision..
This bug still exists...not often but still to many times :(

To the problem about steatlth ...I will try to find a way to reproduce the problem soon...current I do not know why or when this problem occures
I´m very sorry for these vague information

**Comment by Wattiqelumes** [comment]
This can be closed, really pointless and not able to reproduce.

**Comment by tobmaps** [comment]
bug with Shadowform hack-fixed in 5f6fec77184aad0c98d3162ebaffcc4cb80e2777
problem with Stealth i can't reproduce
